In [ ]:
# numpy library is required for this code to run


In [4]:
list = [1, 2, 3, 4, 5] * 1000  # regular python list
print(list)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 

In [6]:
# Difference between numpy array and python list
l = [1, 2, 3, 4, 5] 
print(l)

[1, 2, 3, 4, 5]


In [7]:
l.append(6)

In [8]:
print(l)

[1, 2, 3, 4, 5, 6]


In [16]:
l.pop()

6

In [17]:
print(l)

[1, 2, 3, 4, 5]


In [9]:
import numpy as np

In [14]:
arr = np.array([[1, 2, 3, 4, 5],
                [1, 9, 3, 5, 6]])  # numpy array

In [15]:
arr.T

array([[1, 1],
       [2, 9],
       [3, 3],
       [4, 5],
       [5, 6]])

In [ ]:
arr1 = np.array([[7, 8, 9, 10, 11],
                [12, 13, 14, 15, 16]])

In [20]:
# Give marks of student arr

In [23]:
marks = np.array([[88, 98, 76],
                   [97, 89, 85],
                   [92, 84, 85]])

In [25]:
marks.mean(axis=0)  # mean of columns

array([92.33333333, 90.33333333, 82.        ])

In [26]:
marks.max(axis=1)  # max of rows

array([98, 97, 92])

In [ ]:

new_row = np.array([[95, 96, 90]])
marks = np.insert(marks, 2, new_row, axis=0)

In [37]:
marks

array([[88, 98, 76],
       [97, 89, 85],
       [95, 96, 90],
       [92, 84, 85]])

In [45]:
marks[0][1]

np.int64(98)

In [40]:
# binary search tree
class Node:
    def __init__(self, key):
        self.left = None
        self.right = None
        self.val = key
    def insert(self, root, key):
        if root is None:
            return Node(key)
        else:
            if root.val == key:
                return root
            elif root.val < key:
                root.right = self.insert(root.right, key)
            else:
                root.left = self.insert(root.left, key)
        return root
    def inorder(self, root):
        if root:
            self.inorder(root.left)
            print(root.val)
            self.inorder(root.right)
    def search(self, root, key):
        if root is None or root.val == key:
            return root
        if root.val < key:
            return self.search(root.right, key)
        return self.search(root.left, key)
    def display(self, root, level=0):
        if root is not None:
            self.display(root.right, level + 1)
            print(' ' * 4 * level + '->', root.val)
            self.display(root.left, level + 1)
    def minValueNode(self, node):
        current = node
        while current.left is not None:
            current = current.left
        return current
# Example usage:
r = Node(50)
r = r.insert(r, 30) 
r = r.insert(r, 20)
r = r.insert(r, 40)
r = r.insert(r, 70)
r = r.insert(r, 60)
r = r.insert(r, 80)
r.display(r)
print(f"Inorder traversal: {r.inorder(r)}")

        -> 80
    -> 70
        -> 60
-> 50
        -> 40
    -> 30
        -> 20
20
30
40
50
60
70
80
Inorder traversal: None


In [58]:
arr = np.array([1,2,3,4,5,6])


In [59]:
arr2 = arr + 2
arr2

array([3, 4, 5, 6, 7, 8])

In [2]:
import time

In [3]:
lager_list = list(range(1000000))
start = time.time()
lager_list = [x * 2 for x in lager_list]
end = time.time()

In [4]:
take_time_list = end - start

In [5]:
print(take_time_list)

0.05902361869812012


In [7]:
import numpy as np

In [8]:
np_large = np.array(list(range(1000000)))
start = time.time()
np_large = np_large * 2
end = time.time()

In [10]:
print(end-start)

0.003999471664428711


# **Creating Array**

In [11]:
arr = np.array([1,2,3,4,5])

In [13]:
arr = np.asarray(arr)

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
arr = np.arange(10)

In [16]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
arr = np.linspace(0, 1, 5)

In [18]:
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [19]:
arr = np.zeros((3,4))

In [20]:
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
arr = np.ones((2,3))

In [22]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
arr = np.empty((2,3))

In [26]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
arr5 = np.empty((2,3), dtype=int)

In [28]:
arr5

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [29]:
arr5 = np.empty((2,3), dtype=int)
arr5

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [30]:
arr = np.full((2,3), 7)

In [31]:
print(arr)

[[7 7 7]
 [7 7 7]]


In [36]:
arr = np.eye(4,3,4)

In [37]:
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
arr = np.identity(4)

In [35]:
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
arr = np.random.rand(2,3)

In [41]:
print(arr)

[[0.08354587 0.4737765  0.03060296]
 [0.32124396 0.38207525 0.26069798]]


# **Array Attributes**

In [98]:
arr = np.arange(12).reshape(3,4)

In [99]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
arr.shape

(3, 4)

In [101]:
arr.ndim

2

In [102]:
arr.size

12

In [103]:
arr.dtype

dtype('int64')

In [104]:
arr.itemsize

8

In [105]:
arr.nbytes

96

In [106]:
arr.strides

(32, 8)

In [107]:
arr.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
arr.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
# Indexing 
arr[1][0]

np.int64(4)

In [110]:
# Slicing 
arr[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [111]:
mask = arr % 2 == 0
print(mask)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [112]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

# *Reshaping and Manipulation*

In [113]:
arr.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
arr = np.arange(20)

In [115]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [116]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [117]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [118]:
arr.resize(5,4)

In [119]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [120]:
arr.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [121]:
arr1 = np.swapaxes(arr, 0, 1)

In [122]:
arr1

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [123]:
arr1 = np.moveaxis(arr, 0, 1)

In [124]:
arr1

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [125]:
arr.mean()

np.float64(9.5)

In [126]:
arr1 = np.argmax(arr,1)

In [127]:
print(arr1)

[3 3 3 3 3]


In [129]:
arr = np.arange(16).reshape(4,4)

In [145]:
arr = np.array([[2,4,6],
                [1,2,3],
                [3,6,9]])

In [146]:
np.linalg.det(arr)

np.float64(0.0)